{% set name = "hipscat-import" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hipscat-import/archive/v{{ version }}.tar.gz
  sha256: 06d613fc1dbd928ed7009934ce9fd473aa6a9cb53dbc3a243a09715a9ce7cde5

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - dask-core
    - distributed
    - deprecated
    - healpy
    - hipscat >=0.2.0
    - ipykernel
    - pandas <2.1.0
    - pyarrow
    - pyyaml
    - tqdm
    - numpy <1.25
    - fsspec <=2023.9.2

test:
  imports:
    - hipscat_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - ray-core
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hipscat-import
  summary: 'A HiPSCat astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
    - jeremykubica
    - drewoldag
    - delucchi-cmu
