{% set name = "hipscat-import" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hipscat-import/archive/v{{ version }}.tar.gz
  sha256: 04d567263fe375b49a11fa2f668e147eb272d0376d4115e39daa888b496bd6ce

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - dask-core >=2024.3.0
    - distributed >=2024.3.0
    - deprecated
    - healpy
    - hipscat >=0.3.8
    - ipykernel
    - numpy <2
    - pandas
    - pyarrow
    - pyyaml
    - scipy
    - tqdm
    - numpy

test:
  imports:
    - hipscat_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - ray-core
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hipscat-import
  summary: 'A HiPSCat astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
    - jeremykubica
    - drewoldag
    - delucchi-cmu
